version: '3.7'
services:
  grpc-client-comp:
    container_name: grpc-client-comp
    restart: always
    build:
      context: ./grpc_client
      dockerfile: Dockerfile
    environment:
      - SERVER_HOST=grpc-server-comp:50051
  grpc-server-comp:
    container_name: grpc-server-comp
    restart: always
    build:
      context: ./grpc_server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=:50051